SNSA/NEXT

README.md
gulpfile.js

NEXT-23 Change gulp launch to gulp dev

---

.jshintrc
client/js/constants.js
client/js/main.js

NEXT-24 Add default nickname constant

---

client/js/connector.js
client/js/main.js

Use one of the following scenarios:
* Select `region`, then press `findFfa` or `findParty`.
* Fill `token`, then press `connectParty`.
* Fill `ws` (and optionally fill `token`), then press `directConnect`. May be used for connecting to ogar servers.
Closes #8.

Support party game mode

---

.jscsrc
client/js/animated-value.js
client/js/ball-view.js
client/js/connector.js
client/js/constants.js
client/js/controller.js
client/js/misc.js
client/js/pointer.js
client/js/viewer.js
gulpfile.js
package.json

This fixes #11, now you can verify your code stype by `gulp lint`

NEXT-11 Add linters

---

gulpfile.js

Lint gulpfile.js itself

---

client/js/animated-value.js
client/js/ball-view.js
client/js/controller.js
client/js/pointer.js
client/js/viewer.js

Use ES6 classes instead of prototypes

---

.travis.yml
README.md

NEXT-12 Introduce Travis-CI

---

.travis.yml

NEXT-48 Integrate travis with gitter

---

.travis.yml
README.md
client/index.html
deploy.sh
userscripts/next.chrome.js

NEXT-43 Auto deploy new version of NEXT

---

.gitignore
.travis.yml
config.js

Revert "NEXT-52 Ignore config.js"

---

.jshintrc
client/js/agario-client/Account.js
client/js/agario-client/Ball.js
client/js/agario-client/Packet.js
client/js/agario-client/client.js
client/js/agario-client/servers.js
client/js/controller.js
client/js/main.js
config.js
gulpfile.js
package.json

This fixes #5 
I tried many ways to test agario-client locally during development but failed. That's why I will integrate it to NEXT to simplify NEXT's development. Later when our agario-client is stable, we can separate it to another project if we want.

NEXT-5 Integrate agario-client to NEXT

---

client/js/ball-view.js

Deletes useless balls (fixes #33)

Fixed memory leak bug

---

client/css/layout.css
client/index.html
client/js/controller.js
client/js/dom.js
client/js/viewer.js
config.js
package.json

NEXT-27 Introduce bootstrap to replace dat.gui

---

client/js/agario-client/client.js
client/js/controller.js

NEXT-64 Fix leaderboard

---

client/index.html

NEXT-75 Indicate that this is a test version of NEXT

---

client/js/controller.js

NEXT-74 Do not use jQuery in controller.js

---

client/js/ball-view.js

Display your mass and not your radius.

---

client/js/ball-view.js
client/js/viewer.js

Improvements on animations.

---

client/js/pointer.js

Disallow duplicate key press events.

---

client/js/ball-view.js

Closes #87.
Changes:
- Changed font and stroke.
- Changed virus color.

Enhance graphics.

---

client/index.html
client/js/controller.js
client/js/dom.js
client/js/pointer.js
client/js/viewer.js

Added spectate mode.

---

client/js/ball-view.js

NEXT-9 Improve ball shape by reducing scale

---

client/js/ball-view.js
client/js/viewer.js

This fully destroys balls and optimizes the zsort function. Closes #92.

NEXT-92 Enhance performance

---

README.md
deploy.sh
userscripts/next.firefox.user.js

NEXT-81 Create userscript for Firefox
